#!/usr/bin/expect
set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set admin admin
set mpass ioctl960
set prompt ":~\$"
set send_human {.8 .8 .8 .8 100}
set timeout -1
spawn ./start
match_max 100000
expect "Connected" {send "\r"}
expect { 
	" login:" {  		
		send "$admin\r"
		exp_continue 
	 	  }
        "Password: " {
		send "$mpass\r\r"
		exp_continue
		    }
	"$prompt " { 
		send "\r"
		}
	-re ".*" {
		send "cd ~\r"
		}
	}


puts "logging out!!"
expect "$prompt " {send "logout\r"}
expect " login:" {send "\r"}
expect " login:" {send -h "~."}
expect eof
